try {
    console.log("Checking")

error
    console.log("Checked")
} catch(error) {
    console.log("Failed To Check Because of error");
    console.log(error)
}